name: check for igloos

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check for igloos
        run: |
          curl --silent --head -X POST -H "Content-Type: application/x-www-form-urlencoded" "https://igloos.vercel.app/?index"
