name: check for igloos

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check for igloos
        run: curl -s -X GET "https://igloos.now.sh/run"
